### ISSUE TITLE
Construction using seconds is not accurate

### ISSUE THREAD

**Issue by julaudo** [eoyilmaz/timecode#22] opened 2020-03-12 10:26 UTC
The folloing code

```
    from timecode import Timecode
    seconds = 0
    for _ in range(12):
        seconds += 0.04
        print(Timecode(framerate=25, start_seconds=seconds).frames)
```
prints
```
1
2
3
4
5
6
7
8
9
10
10
11
```

This is because of the float_to_tc method:
```
    def float_to_tc(self, seconds):
        """set the frames by using the given seconds
        """
        return int(seconds * self._int_framerate)
```
If the float is not exactly represented, the result may not be accurate.
In the example : 
`int(0.43999999999999995*25)=int(10.999999999999998)=10`

It would be safer to round the result before casting to integer:
```
    def float_to_tc(self, seconds):
        """set the frames by using the given seconds
        """
        return int(round(seconds * self._int_framerate))
```

**Comment by eoyilmaz** [comment] 2020-04-21 20:45
Sorry but using Round is not a solution and more over this is not a bug.

Let me try to explain.

This is like trying to fix a weak point of computer arithmetic (not all float numbers are represented in modern computers) plus a wrong algorithm that exaggerates this problem (continuously adding float numbers to each other) with something else (round). And, 10.999999999999998 is still in range of frame 10. This is not wrong. Expecting to end up at 11th frame is not the correct assumption.

Think the frames as boxes (or time ranges) that covers the whole range from number 10 to 11 or [10, 11). So any float number between 10 and 11 is frame 10. If we use Round as you suggested, we will assume that anything after 10.50 is frame 11 and this is not correct.

```
10                       11                       12                       13
+------------------------+------------------------+------------------------+
|                        |                        |                        |                         
|   Anything here        |                        |                        |                         
|   is Frame 10          |                        |                        |                         
|                        |                        |                        |                         
```
I am closing this issue.

**Closed by eoyilmaz** 2020-04-21 20:45 UTC
