### ISSUE TITLE
Comparison operators throw an Error?

### ISSUE THREAD

**Issue by caliban17** [eoyilmaz/timecode#28] opened 2020-08-12 05:11 UTC
This is probably a real noob question but I cant get the comparison operators to work
```
        from timecode import Timecode

        tcI = Timecode('25', '03:12:49:02')
        tcChunkStart = Timecode('25', '03:12:51:04')
        if tcI < tcChunkStart:
            #do something
```
when run gets error on the if statement: 
```TypeError: '<' not supported between instances of 'Timecode' and 'Timecode'. ```  

Seems weird as arithmetric functions work fine  ie. 
```
    tcTest=tcI + tcOut
```
Any help gratefully appreciated

**Comment by eoyilmaz** [comment] 2020-08-18 11:38
Your code works for me. Which version are you using?

**Comment by aki-sud** [comment] 2020-08-26 06:19
same issue coming on 1.2.0 version

**Comment by eoyilmaz** [comment] 2020-08-26 06:37
Here is my output for both Python 2.7 and 3.7:

```
Python 2.7.18 (default, Jul 20 2020, 00:00:00) 
[GCC 10.1.1 20200507 (Red Hat 10.1.1-1)] on linux2
>>> from timecode import Timecode
>>> tcI = Timecode('25', '03:12:49:02')
... tcChunkStart = Timecode('25', '03:12:51:04')
>>> if tcI < tcChunkStart:
...     print("tcI is smaller than tcChunkStart")
...     
tcI is smaller than tcChunkStart
```



```
Python 3.7.8 (default, Aug 13 2020, 12:31:56) 
[GCC 10.2.1 20200723 (Red Hat 10.2.1-1)] on linux
>>> from timecode import Timecode
>>> tcI = Timecode('25', '03:12:49:02')
... tcChunkStart = Timecode('25', '03:12:51:04')
>>> if tcI < tcChunkStart:
...     print("tcI is smaller than tcChunkStart")
...     
tcI is smaller than tcChunkStart
```

**Comment by aki-sud** [comment] 2020-08-26 06:43
I am using windows ,python 3.8.3

**Comment by eoyilmaz** [comment] 2020-08-26 07:49
Here is the output for Python 3.8.5

```
Python 3.8.5 (default, Aug 12 2020, 00:00:00) 
[GCC 10.2.1 20200723 (Red Hat 10.2.1-1)] on linux
>>> from timecode import Timecode
>>> tcI = Timecode('25', '03:12:49:02')
... tcChunkStart = Timecode('25', '03:12:51:04')
>>> if tcI < tcChunkStart:
...     print("tcI is smaller than tcChunkStart")
...     
tcI is smaller than tcChunkStart
```

So it seems that I can not reproduce the error. Are you guys using Windows or OSX. May be it is something related to OS.

**Comment by eoyilmaz** [comment] 2020-08-26 07:54
> same issue coming on 1.2.0 version

By the way the latest code version is 1.2.2

**Comment by aki-sud** [comment] 2020-08-26 16:57
using windows 7
(latest version available on pip is 1.2.0)

**Comment by eoyilmaz** [comment] 2020-08-26 20:43
I've updated PyPI. Please upgrade to the latest version.

**Comment by aki-sud** [comment] 2020-08-26 20:51
working on the latest version.
Thanks.

**Comment by eoyilmaz** [comment] 2020-08-27 01:02
:+1: closing

**Closed by eoyilmaz** 2020-08-27 01:02 UTC
